<!DOCTYPE html>
<html lang="ru">
	<head>
		<title>Наше меню | Сеть кофеен "Fabae coffeae"</title>
		<link rel="stylesheet" type="text/css" href="../../../Users/Катя/Desktop/Вузовские штуки/2 курс/КвИиППС/лр 4/css/stylemy.css">
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initialscale=1.0">
		<link rel="stylesheet" href="../../../Users/Катя/Desktop/Вузовские штуки/2 курс/КвИиППС/лр 4/css/bootstrap.min.css">
	</head>
	<body>
		<div class="container">
			<div class="row">
				<div class="col-lg-12" >
				<!--элементы шапки сайта-->
				<h2><a href="index.inc">Сеть кофеен "Fabae coffeae"</a></h2>
			</div>
			<div class="col-lg-12">
			<!--меню сайта-->
			<div id="mainmenu">
				<ul> <!-- Описание ссылок в меню и сами ссылки. -->
					<li>
						<a href="о about.inc">О нас</a></li>
					<li>
						<a href="menu.inc">Наше меню</a></li>
					<li>
						<a href="contact.inc">Контакты</a></li>
					<li>
						<a href="gbook.inc">Гостевая книга</a></li>
				</ul>
			</div>
			<!--Конец меню сайта-->
			</div>
			<div class="col-lg-12" >
			<!-- Область Контента -->
			<div id="content">
			<h3 align="center"><i>Наше</i> меню</h3> 
			<p>Наше меню содержит разнообразные виды кофе и напитков. В уникальном калейдоскопе вкусов каждый найдет себе что-нибудь по нраву ;)</p>
				<!-- здесь располагается таблица меню-->
			<table class="table">
 <thead>
<tr>
<th>Напитки</th>
<th>100 мл</th>
<th>350 мл</th>
<th>450 мл</th>
</tr>
</thead>
 <tbody>
 <tr>
 <td>Американо</td>
 <td>70 ₽</td>
 <td>110 ₽</td>
 <td>150 ₽</td>
 </tr>
 <tr>
 <td>Капучино</td>
 <td>70 ₽</td>
 <td>110 ₽</td>
 <td>140 ₽</td>
 </tr>
 <tr>
 <td>Латте</td>
 <td></td>
 <td>110 ₽</td>
 <td>150 ₽</td>
 </tr>
 <tr>
 <td>Эспрессо</td>
 <td>80 ₽</td>
 <td></td>
 <td></td>
 </tr>
 <tr>
 <td>Какао с маршмеллоу</td>
 <td></td>
 <td>150 ₽</td>
 <td>180 ₽</td>
 </tr>
 <tr>
 <td>Чай в ассортименте</td>
 <td></td>
 <td>110 ₽</td>
 <td>150 ₽</td>
 </tr>
 </tbody>
			</table>
			</div>
			<!--конец области контента-->
			</div>
			<div id="clear">
			</div>
			<div class="col-lg-12">
			<!--Подвал сайта-->
			<div id="footer">
				<footer>
					<p align="left"><small>"Fabae coffeae". All Rights Reserved. ©</small></p>
					<p align="left"><small>2015-2020</small></p>
					<p align="center"><small>О компании<a href="о нас.html"></a></small></p>
					<p align="center"><small>Наше меню<a href="наше меню.html"></a></small></p>
					<p align="center"><small>Контакты<a href="контакты.html"></a></small></p>
				</footer>
			</div>
		</div>
		</div>
		</div>
	</body>
</html>